import type { TailwindColor } from "~/tailwind//types";

export const colorTextStyles: Record<TailwindColor, string> = {
  emerald: "bg-emerald-500 focus:bg-emerald-400 hover:bg-emerald-600",
  red: "bg-red-500 focus:bg-red-400 hover:bg-red-600",
  orange: "bg-orange-500 focus:bg-orange-400 hover:bg-orange-600",
  yellow: "bg-yellow-500 focus:bg-yellow-400 hover:bg-yellow-600",
  green: "bg-green-500 focus:bg-green-400 hover:bg-green-600",
  teal: "bg-teal-500 focus:bg-teal-400 hover:bg-teal-600",
  blue: "bg-blue-500 focus:bg-blue-400 hover:bg-blue-600",
  indigo: "bg-indigo-500 focus:bg-indigo-400 hover:bg-indigo-600",
  purple: "bg-purple-500 focus:bg-purple-400 hover:bg-purple-600",
  pink: "bg-pink-500 focus:bg-pink-400 hover:bg-pink-600",
  fuchsia: "bg-fuchsia-500 focus:bg-fuchsia-400 hover:bg-fuchsia-600",
  violet: "bg-violet-500 focus:bg-violet-400 hover:bg-violet-600",
  cyan: "bg-cyan-500 focus:bg-cyan-400 hover:bg-cyan-600",
  gray: "bg-gray-500 focus:bg-gray-400 hover:bg-gray-600",
  coolGray: "bg-coolGray-500 focus:bg-coolGray-400 hover:bg-coolGray-600",
  trueGray: "bg-trueGray-500 focus:bg-trueGray-400 hover:bg-trueGray-600",
  warmGray: "bg-warmGray-500 focus:bg-warmGray-400 hover:bg-warmGray-600",
  amber: "bg-amber-500 focus:bg-amber-400 hover:bg-amber-600",
  lime: "bg-lime-500 focus:bg-lime-400 hover:bg-lime-600",
  rose: "bg-rose-500 focus:bg-rose-400 hover:bg-rose-600",
  sky: "bg-sky-500 focus:bg-sky-400 hover:bg-sky-600",
  black: "bg-black focus:bg-black hover:bg-black",
  white: "bg-white focus:bg-white hover:bg-white",
  transparent: "bg-transparent focus:bg-transparent hover:bg-transparent",
  current: "bg-current focus:bg-current hover:bg-current",
  primary: "bg-primary focus:bg-primary hover:bg-primary",
  secondary: "bg-secondary focus:bg-secondary hover:bg-secondary",
  success: "bg-success focus:bg-success hover:bg-success",
  info: "bg-info focus:bg-info hover:bg-info",
  warning: "bg-warning focus:bg-warning hover:bg-warning",
  danger: "bg-danger focus:bg-danger hover:bg-danger",
  blueGray: "bg-blueGray-500 focus:bg-blueGray-400 hover:bg-blueGray-600",
  light: "bg-light focus:bg-light hover:bg-light",
  dark: "bg-dark focus:bg-dark hover:bg-dark",
};
